#!/usr/bin/env python

def build(bld):
  bld.install_files('${PREFIX}/include/beam', bld.path.ant_glob('*.h'))

  bld(features = 'cxx cprogram gtest',
      source = 'scoped_ptr_test.cc',
      target = 'scoped_ptr_test')

  bld.recurse('log')
  bld.recurse('tr1')
